### ISSUE TITLE
muzzley.py start error

### ISSUE THREAD

**Issue by davidrib** [muzzley/arduino-ciao-muzzley-connector#1]
file: /usr/lib/python2.7/ciao/ciao.log
file content:

root@linino:/usr/lib/python2.7/ciao# cat   ciao.log 
2016-02-25 14:29:36,669 DEBUG ciao - Ignoring mqtt configuration: connector not enabled
2016-02-25 14:29:36,681 DEBUG ciao - Loaded configuration for xmpp connector
2016-02-25 14:29:36,691 DEBUG ciao - Loaded configuration for muzzley connector
2016-02-25 14:29:36,701 DEBUG ciao - Ignoring phant configuration: connector not enabled
2016-02-25 14:29:36,718 INFO ciao.connector.xmpp - Received start command
2016-02-25 14:29:39,735 INFO ciao.connector.muzzley - Received start command
2016-02-25 14:29:40,823 ERROR ciao.connector.muzzley - Exception during muzzley start: Command '[u'/usr/lib/python2.7/ciao/connectors/muzzley/muzzley.py', u'geoplatform.muzzley.com', u'8883', u'global-manager.muzzley.com', u'wlan0', u'Go_Daddy_Class_2_CA.crt']' returned non-zero exit status 1

file: /var/log/run-ciao.log  NOT EXIST
file: /var/log/muzzley.log NOT EXIST

the following python module dependencies on the Linino OS:
OK to install: distribute 
OK to install: python-openssl
NOT OK to install: paho-mqtt (maybe python-paho-mqtt???)
NOT OK to install: urllib3 (not find)
NOT OK to install: requests (maybe python-requests???)

Can someone point-me to the right direction??

**Comment by davidrib** [comment]
Installed pakages:

Remove  alljoyn     14.12a-1
Remove  alljoyn-about   14.12a-1
Remove  alljoyn-c   14.12a-1
Remove  alljoyn-config  14.12.00-1
Remove  alljoyn-controlpanel    14.12.00-1
Remove  alljoyn-notification    14.12.00-1
Remove  alljoyn-services_common     14.12.00-1
Remove  avahi-daemon    0.6.31-5
Remove  avahi-dnsconfd  0.6.31-5
Remove  avahi-utils     0.6.31-5
Remove  avrdude     6.1-r1353-1
Remove  base-files  118.2-r41182
Remove  blkid   2.21.2-1
Remove  block-mount     0.2.0-9
Remove  busybox     1.19.4-6
Remove  ca-certificates     20150426
Remove  ciao    0.0.2-1
Remove  cpu-mcu-bridge  1.5.1-1
Remove  curl    7.29.0-1
Remove  dbus    1.4.14-2
Remove  distribute  0.6.21-1
Remove  dnsmasq     2.66-2
Remove  dropbear    2011.54-2
Remove  firewall    2013-06-29
Remove  gnupg   1.4.12-1
Remove  hotplug2    1.0-beta-4
Remove  i2c-tools   3.0.3-1
Remove  iptables    1.4.10-5
Remove  iw  3.14-1
Remove  jshn    2013-10-19-734d28eb1a46358743cf8837c91e5d46695c3b91
Remove  kernel  3.3.8-1-31b547152901f3179f11590e15e76a76
Remove  kmod-ath    3.3.8+2014-05-22-1
Remove  kmod-ath9k  3.3.8+2014-05-22-1
Remove  kmod-ath9k-common   3.3.8+2014-05-22-1
Remove  kmod-cfg80211   3.3.8+2014-05-22-1
Remove  kmod-crypto-aes     3.3.8-1
Remove  kmod-crypto-arc4    3.3.8-1
Remove  kmod-crypto-core    3.3.8-1
Remove  kmod-crypto-hash    3.3.8-1
Remove  kmod-crypto-manager     3.3.8-1
Remove  kmod-fs-ext4    3.3.8-1
Remove  kmod-fs-hfs     3.3.8-1
Remove  kmod-fs-hfsplus     3.3.8-1
Remove  kmod-fs-ntfs    3.3.8-1
Remove  kmod-fs-reiserfs    3.3.8-1
Remove  kmod-fs-vfat    3.3.8-1
Remove  kmod-fuse   3.3.8-1
Remove  kmod-gpio-button-hotplug    3.3.8-1
Remove  kmod-i2c-core   3.3.8-1
Remove  kmod-ipt-conntrack  3.3.8-1
Remove  kmod-ipt-core   3.3.8-1
Remove  kmod-ipt-nat    3.3.8-1
Remove  kmod-ipt-nathelper  3.3.8-1
Remove  kmod-leds-gpio  3.3.8-1
Remove  kmod-ledtrig-default-on     3.3.8-1
Remove  kmod-ledtrig-netdev     3.3.8-1
Remove  kmod-ledtrig-timer  3.3.8-1
Remove  kmod-lib-crc-ccitt  3.3.8-1
Remove  kmod-lib-crc16  3.3.8-1
Remove  kmod-loop   3.3.8-1
Remove  kmod-mac80211   3.3.8+2014-05-22-1
Remove  kmod-nls-base   3.3.8-1
Remove  kmod-nls-cp437  3.3.8-1
Remove  kmod-nls-iso8859-1  3.3.8-1
Remove  kmod-nls-utf8   3.3.8-1
Remove  kmod-ppp    3.3.8-1
Remove  kmod-pppoe  3.3.8-1
Remove  kmod-pppox  3.3.8-1
Remove  kmod-scsi-core  3.3.8-1
Remove  kmod-spi-bitbang    3.3.8-1
Remove  kmod-spi-dev    3.3.8-1
Remove  kmod-spi-gpio   3.3.8-1
Remove  kmod-spi-tty-plain  3.3.8-1
Remove  kmod-usb-core   3.3.8-1
Remove  kmod-usb-storage    3.3.8-1
Remove  kmod-usb2   3.3.8-1
Remove  kmod-video-core     3.3.8-1
Remove  kmod-wdt-ath79  3.3.8-1
Remove  ldattach    2.21.2-1
Remove  libassuan   2.0.2-1
Remove  libavahi    0.6.31-5
Remove  libavahi-client     0.6.31-5
Remove  libavahi-dbus-support   0.6.31-5
Remove  libblkid    2.21.2-1
Remove  libblobmsg-json     2013-10-19-734d28eb1a46358743cf8837c91e5d46695c3b91
Remove  libbz2  1.0.6-2
Remove  libc    0.9.33.2-1
Remove  libcurl     7.29.0-1
Remove  libcyassl   1.6.5-1
Remove  libdaemon   0.14-2
Remove  libdbus     1.4.14-2
Remove  libdw   0.155-1
Remove  libelf1     0.155-1
Remove  libexpat    2.0.1-1
Remove  libffi  3.0.10-1
Remove  libftdi     0.19-1
Remove  libftdi1    1.2-3
Remove  libgcc  4.6-linaro-1
Remove  libgdbm     1.9.1-2
Remove  libgpg-error    1.9-1
Remove  libgpgme    1.3.1-1.dh1
Remove  libip4tc    1.4.10-5
Remove  libip6tc    1.4.10-5
Remove  libiwinfo   44
Remove  libiwinfo-lua   44
Remove  libjson     0.11-2
Remove  libjson-c   0.11-2
Remove  libjson-script  2013-10-19-734d28eb1a46358743cf8837c91e5d46695c3b91
Remove  liblua  5.1.4-8
Remove  libncurses  5.7-5
Remove  libnl   2.0-1
Remove  libnl-tiny  0.1-3
Remove  libopenssl  1.0.1h-1
Remove  libpcre     8.11-2
Remove  libpolarssl     1.2.5-1
Remove  libpthread  0.9.33.2-1
Remove  libreadline     5.2-2
Remove  librt   0.9.33.2-1
Remove  libstdcpp   4.6-linaro-1
Remove  libubox     2013-10-19-734d28eb1a46358743cf8837c91e5d46695c3b91
Remove  libubus     2013-08-08-b20a8a01c7faea5bcc9d34d10dcf7736589021b8
Remove  libubus-lua     2013-08-08-b20a8a01c7faea5bcc9d34d10dcf7736589021b8
Remove  libuci  2013-06-11.1-1
Remove  libuci-lua  2013-06-11.1-1
Remove  libusb  0.1.12-3
Remove  libusb-1.0  1.0.9-1
Remove  libusb-compat   0.1.4-1
Remove  libuuid     2.21.2-1
Remove  libxtables  1.4.10-5
Remove  lowpan-tools    0.3.1
Remove  lua     5.1.4-8
Remove  luci    0.11+svn-1
Remove  luci-app-firewall   0.11+svn-1
Remove  luci-i18n-english   0.11+svn-1
Remove  luci-lib-core   0.11+svn-1
Remove  luci-lib-ipkg   0.11+svn-1
Remove  luci-lib-json   0.11+svn-1
Remove  luci-lib-nixio  0.11+svn-1
Remove  luci-lib-sys    0.11+svn-1
Remove  luci-lib-web    0.11+svn-1
Remove  luci-mod-admin-core     0.11+svn-1
Remove  luci-mod-admin-full     0.11+svn-1
Remove  luci-proto-core     0.11+svn-1
Remove  luci-proto-ppp  0.11+svn-1
Remove  luci-sgi-cgi    0.11+svn-1
Remove  luci-theme-base     0.11+svn-1
Remove  luci-theme-bootstrap    0.11+svn-1
Remove  luci-theme-openwrt  0.11+svn-1
Remove  luci-webpanel-linino    1.0.3-1
Remove  mtd     18.1
Remove  nano    2.2.6-1
Remove  netifd  2013-07-16-2674941b06c1ec67f1aff1bff9212e1372106641
Remove  openssh-sftp-server     6.1p1-1
Remove  opkg    618-3.dh1
Remove  ppp     2.4.5-10
Remove  ppp-mod-pppoe   2.4.5-10
Remove  px5g    1
Remove  pyserial    2.4-1
Remove  python  2.7.3-4
Remove  python-expat    2.7.3-4
Remove  python-firmata  0.9.5-1
Remove  python-json     3_4-1
Remove  python-mini     2.7.3-4
Remove  python-openssl  2.7.3-4
Remove  python-paho-mqtt    1.1-1
Remove  python-requests     2.8.1-1
Remove  rng-tools   3-2
Remove  spacebrew   2.3.0-1
Remove  swap-utils  2.21.2-1
Remove  swconfig    10
Remove  temboo  1.1.0-1
Remove  terminfo    5.7-5
Remove  triggerhappy    0.3.4-1
Remove  uSDaemon    1.0.0-1
Remove  uboot-envtools  2012.04.01-1
Remove  ubus    2013-08-08-b20a8a01c7faea5bcc9d34d10dcf7736589021b8
Remove  ubusd   2013-08-08-b20a8a01c7faea5bcc9d34d10dcf7736589021b8
Remove  uci     2013-06-11.1-1
Remove  uclibcxx    0.2.4-1
Remove  uhttpd  2012-10-30-e57bf6d8bfa465a50eea2c30269acdfe751a46fd
Remove  uhttpd-mod-lua  2012-10-30-e57bf6d8bfa465a50eea2c30269acdfe751a46fd
Remove  uhttpd-mod-tls  2012-10-30-e57bf6d8bfa465a50eea2c30269acdfe751a46fd
Remove  uhttpd-mod-ubus     2012-10-30-e57bf6d8bfa465a50eea2c30269acdfe751a46fd
Remove  usbutils    005-1
Remove  wget    1.16.3-1
Remove  wireless-tools  29-5
Remove  wpad-mini   20131120-1
Remove  yun-scripts     1.2-6
Remove  zlib    1.2.7-1

**Comment by jorgeclaro** [comment]
Hi David,

First of all you need to install the missing libraries. To do that, use the “easy_install” command to install “paho_mqtt", “urllib3" and “requests" libraries.

Ex.: “$ easy_install paho_mqtt"

After that, enable the Ciao MQTT connector, on the conf file: “/usr/lib/python2.7/ciao/conf/mqtt.json.conf“. The Muzzley connector depends on it.

Finally just add some empty files with the name "__ init __.py” (like the ones in the Muzzley connector) on the following folders, to make the MQTT connector code available to the Muzzley connector:
“/usr/lib/python2.7/ciao"
“/usr/lib/python2.7/ciao/connectors"
“/usr/lib/python2.7/ciao/connectors/mqtt"

The file: "/var/log/muzzley.log” will be created as soon as the connector starts, and the file “/var/log/run-ciao.log” will be also created as soon as ciao starts ( accordingly with the path defined on the "run-ciao” file. It may have been changed by the ciao team, just check it).

If any other doubt, just let me know.
Jorge Claro

**Comment by davidrib** [comment]
thanks for the info!

now first I have this:
root@linino:/usr/lib/python2.7/ciao# cat /var/log/muzzley.log 
INFO:muzzley.client:Could not read the stored device_key

Next:
root@linino:/etc/muzzley# cat /var/log/muzzley.log 
INFO:muzzley.client:Read the the stored device_key sucessfully

he himself created this file!
root@linino:/etc/muzzley# ls
devicekey.key      muzzley.json.conf

Thanks for the fast response!
David Ribeiro

**Comment by jorgeclaro** [comment]
Hi David,

The device_key, is basically the unique identifier of your Arduino on the Muzzley Cloud. It will be generated automatically by our could, and will be stored on the Arduino, right next to the muzzley.log file.

At this moment you should create a profile spec on our developers web page, and complete the muzzley.json.conf with your Muzzley app credentials and specification.

Cheers,
Jorge Claro

**Comment by davidrib** [comment]
The devicekey.key is  right next to the muzzley.json.conf file, the var/log/ directory is volatile (I think), the log is always cleaned after reboot.
